# Generated by Django 6.0.6 on 2026-07-10 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('join', 'Join'), ('leave', 'Leave'), ('kick', 'Kick'), ('ban', 'Ban'), ('mute', 'Mute'), ('invite', 'Invite'), ('role_change', 'Role change'), ('other', 'Other')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='common_audi_target__65ba7e_idx'), models.Index(fields=['actor', '-created_at'], name='common_audi_actor_i_bd962b_idx')],
            },
        ),
    ]
