# Generated by Django 6.0.6 on 2026-07-10 11:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.CharField(db_index=True, max_length=140)),
                ('sender_key', models.CharField(db_index=True, max_length=64)),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_color', models.CharField(default='#64748B', max_length=9)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice'), ('file', 'File'), ('system', 'System')], default='text', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('attachment_url', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('previous_text', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='messaging.message')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('emoji', models.CharField(max_length=16)),
                ('actor_key', models.CharField(db_index=True, max_length=64)),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message')),
            ],
        ),
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reader_key', models.CharField(db_index=True, max_length=64)),
                ('reader_name', models.CharField(blank=True, max_length=120)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='messaging.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='messaging_m_room_5abe90_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'is_deleted', 'created_at'], name='messaging_m_room_b24ff5_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('message', 'emoji', 'actor_key'), name='uniq_reaction_per_actor'),
        ),
        migrations.AddIndex(
            model_name='readreceipt',
            index=models.Index(fields=['message', 'reader_key'], name='messaging_r_message_172321_idx'),
        ),
        migrations.AddConstraint(
            model_name='readreceipt',
            constraint=models.UniqueConstraint(fields=('message', 'reader_key'), name='uniq_receipt_per_reader'),
        ),
    ]
