# Generated by Django 6.0.6 on 2026-07-10 11:18

import apps.messaging.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('player_key', models.CharField(db_index=True, max_length=64)),
                ('player_name', models.CharField(blank=True, max_length=120)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='messaging.message')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'player_key'), name='uniq_play_per_listener')],
            },
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('audio', models.FileField(max_length=255, upload_to=apps.messaging.models._voice_upload_path)),
                ('mime', models.CharField(default='audio/webm', max_length=60)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('waveform', models.JSONField(blank=True, default=list, help_text='Normalised 0-100 amplitude bars.')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='messaging.message')),
            ],
            options={
                'indexes': [models.Index(fields=['message'], name='messaging_v_message_3ef115_idx')],
            },
        ),
    ]
